# Generated by Django 4.2.16 on 2024-09-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
