# Generated by Django 4.2.16 on 2024-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npoapi', '0002_alter_project_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Unnamed Project', max_length=255),
        ),
    ]
